name: Code Lint Check

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches-ignore: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint v8
        run: npm install --save-dev eslint@8

      - name: Run ESLint
        run: npx eslint .
